package com.esirong.timer;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ADDRESS.
 */
public class Address {

    private Long id;
    private String name;
    private Integer pos;

    public Address() {
    }

    public Address(Long id) {
        this.id = id;
    }

    public Address(Long id, String name, Integer pos) {
        this.id = id;
        this.name = name;
        this.pos = pos;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getPos() {
        return pos;
    }

    public void setPos(Integer pos) {
        this.pos = pos;
    }

}
