package com.esirong.timer;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TASK__LABEL.
 */
public class Task_Label {

    private Long id;
    private long taskId;
    private long labelId;

    public Task_Label() {
    }

    public Task_Label(Long id) {
        this.id = id;
    }

    public Task_Label(Long id, long taskId, long labelId) {
        this.id = id;
        this.taskId = taskId;
        this.labelId = labelId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getTaskId() {
        return taskId;
    }

    public void setTaskId(long taskId) {
        this.taskId = taskId;
    }

    public long getLabelId() {
        return labelId;
    }

    public void setLabelId(long labelId) {
        this.labelId = labelId;
    }

}
